In [1]:
34+34

68

In [4]:
#"hello everyone"

# Heading1
## Heading2
### Heading3
....
###### Heading6

### ML Workshop
 - *Day3* --italic text

#### Font styles
- I am *italic* in this sentence
- I am **bold text**
- I am ***bold italic***

#### Python
- It is a general purpose high level and interpreted language
- It is semi-object oriented programming language
    - **General purpose**
         - It is used for web development,application development,system software development etc..
    - **high level language**
        - it is understandable by the user
    - **interpreted language**
        - it gives the us the line by line execution
        
- It is the building block of all current running technologies such as Data Science,Artificial Intelligence, Machine Learning,IOT, Robotics etc...


- Python is easy to learn and simple to code
    - new line
        - next line
            - next next line
- syntax free language
- case sensitive and space sensitive language

### Links:
Data science 
[Readmore](https://vignanits.ac.in/)


### Learning path:

* Statistics
* Data Structures
* Programming languages
* Data analysis
* Machine learning

### Data:

Data is a collection of facts such as words,numbers,observations, measurements, etc

### Types of data:

* Quantitative
    * Discreate
        - Exact values like strength in a class,family members
    * Continuous
        - Floating values like height and weight

* Qualitative
    * Order
        - Students Ids
    * Un-order
        - names & colours
    
### Data formates/represent

* Structured
    - tabular data
* Unstructured
    - data in any website
* Semi-Structured
    * Ex: xml,json


### Data analysis:

Data analysis is a process of data cleaning,data translation and data extraction

* Python
    * Numpy
    * Pandas
    * Data visulization
        * Matplotlib
        * Seaborn


### Numpy:
* Numpy stands for numerical python.
* Numpy is python lib
* It is used for data calculations

* 1D => Vector
* 2D => Matrix
* 3D,4D..ND => Multi Dimentional array




In [5]:
# 1D array
# pip install numpy
import numpy as np
np.__version__

'1.16.5'

In [6]:
a=np.array([10,20,30,"naku teliyadu","nuve telusuko"])
a

array(['10', '20', '30', 'naku teliyadu', 'nuve telusuko'], dtype='<U13')

In [8]:
a=np.array([10,20,30,40,50.67])
a

array([10.  , 20.  , 30.  , 40.  , 50.67])

In [9]:
a=np.array([10,20,30,40,50.67,"string"])
a

array(['10', '20', '30', '40', '50.67', 'string'], dtype='<U32')

In [12]:
a=np.array([10,20,30,40,50])
print("array is ",a)
print("Data type of array is ",a.dtype)
print("shape of array is ",a.shape)
print("Dimentions of array is ",a.ndim)

array is  [10 20 30 40 50]
Data type of array is  int32
shape of array is  (5,)
Dimentions of array is  1


In [14]:
# access the data
for i in a:
    print(i,end=" ")

10 20 30 40 50 

In [19]:
a=np.array([10,20,30,40,50,60,70])
a[3]
a[5:2]
a[-2:-5]
a[-5:-2]
a[:5:2]

array([10, 30, 50])

In [20]:
a[2]=300
a

array([ 10,  20, 300,  40,  50,  60,  70])

In [22]:
a[4:]=[500,600,700]
a

array([ 10,  20, 300,  40, 500, 600, 700])

In [23]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [24]:
#2D array => list->list
a=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [25]:
print("array is ",a)
print("Data type of array is ",a.dtype)
print("shape of array is ",a.shape)
print("Dimentions of array is ",a.ndim)

array is  [[10 20 30]
 [40 50 60]
 [70 80 90]]
Data type of array is  int32
shape of array is  (3, 3)
Dimentions of array is  2


In [26]:
a1=np.array([
    [10,20],
    [30,40],
    [700,400]
])
print("array is ",a1)
print("Data type of array is ",a1.dtype)
print("shape of array is ",a1.shape)
print("Dimentions of array is ",a1.ndim)

array is  [[ 10  20]
 [ 30  40]
 [700 400]]
Data type of array is  int32
shape of array is  (3, 2)
Dimentions of array is  2


In [27]:
a=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [31]:
a[2][1]
a[1][1:]
a[1,1:]

array([50, 60])

In [33]:
# 3D array => list->list->list
a=np.array([[[10,20],[30,40]]])
print("array is ",a)
print("Data type of array is ",a.dtype)
print("shape of array is ",a.shape)
print("Dimentions of array is ",a.ndim)

array is  [[[10 20]
  [30 40]]]
Data type of array is  int32
shape of array is  (1, 2, 2)
Dimentions of array is  3


In [36]:
# change the dimentions of array
a=np.array([10,20,30,40,50])
print("array is ",a)
print("Data type of array is ",a.dtype)
print("shape of array is ",a.shape)
print("Dimentions of array is ",a.ndim)
print("-----after 2d conversion------")
a=np.array([10,20,30,40,50],ndmin=2)
print("array is ",a)
print("Data type of array is ",a.dtype)
print("shape of array is ",a.shape)
print("Dimentions of array is ",a.ndim)


array is  [10 20 30 40 50]
Data type of array is  int32
shape of array is  (5,)
Dimentions of array is  1
-----after 2d conversion------
array is  [[10 20 30 40 50]]
Data type of array is  int32
shape of array is  (1, 5)
Dimentions of array is  2


In [37]:
a=np.array([10,20,30,40,50])
print("array is ",a)
print("Data type of array is ",a.dtype)
print("shape of array is ",a.shape)
print("Dimentions of array is ",a.ndim)
print("-----after 3d conversion------")
a=np.array([10,20,30,40,50],ndmin=3)
print("array is ",a)
print("Data type of array is ",a.dtype)
print("shape of array is ",a.shape)
print("Dimentions of array is ",a.ndim)


array is  [10 20 30 40 50]
Data type of array is  int32
shape of array is  (5,)
Dimentions of array is  1
-----after 3d conversion------
array is  [[[10 20 30 40 50]]]
Data type of array is  int32
shape of array is  (1, 1, 5)
Dimentions of array is  3


In [40]:
# arange
a=np.arange(10,20,3)
a

array([10, 13, 16, 19])

In [45]:
# reshape
a=np.arange(10).reshape(1,10)
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [49]:
a[2]

array([[30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [54]:
#a=np.arange(45).reshape(9,5)
a=np.arange(45).reshape(3,3,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [59]:
th=np.arange(32).reshape(2,4,4) # no.of arrays,size of each array # 3d array
print(th)

th[1,2:,1:3] #

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


array([[25, 26],
       [29, 30]])

In [50]:
a[2,2,2:]

array([42, 43, 44])

In [51]:
a[2,0:2,3:]

array([[33, 34],
       [38, 39]])

In [62]:
##aaaabbbzz
# o/p:4a3b2z
st=input()
print(st.count("a"),"a",st.count("b"),"b",st.count("z"),"z",sep="")

aaaaabbbzzz
5a3b3z


In [63]:
# i/p:3b5z2k
#o/p:bbbzzzzzkk
print("b"*3,"z"*5,"k"*2,sep="")

bbbzzzzzkk


In [6]:
al=input()
for index in range(len(al)):
    #print(al[index])
    if al[index].isdigit():
        print(int(al[index])*al[index+1],end="")
        

2j7o
jjooooooo

In [65]:
3*"ruthu"

'ruthuruthuruthu'

In [66]:
"hi"*4

'hihihihi'

In [78]:
if "890".isdigit():
    print("hi")

hi


### Pandas:
* Pandas is python lib for working on datasets.
* It is most powerful lib in datascience
* Series : 1D array
* DataFrame : 2D array



In [7]:
import numpy as np
import pandas as pd

In [8]:
pd.__version__

'0.25.1'

In [9]:
s=pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [10]:
s=pd.Series({10,20,30,40,50})
s

TypeError: 'set' type is unordered

In [11]:
s=pd.Series((10,20,30,40,50))
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [12]:
d={"sno":101,"sname":"nenu chepanu","smarks":"i am failed"}
s=pd.Series(d)
s

sno                101
sname     nenu chepanu
smarks     i am failed
dtype: object

In [15]:
s=pd.Series([10,20,30.66,40,50,"oka string"])
s

0            10
1            20
2         30.66
3            40
4            50
5    oka string
dtype: object

In [16]:
s[2:]

2         30.66
3            40
4            50
5    oka string
dtype: object

In [17]:
# DataFrame
df=pd.DataFrame([10,20,30,40,50])
df

0
0  10
1  20
2  30
3  40
4  50

In [18]:
df=pd.DataFrame({10,20,30,40,50})
df

0
0  40
1  10
2  50
3  20
4  30

In [19]:
df=pd.DataFrame([[10,20,30],[40,50,60],[70,80,90]])
df

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [20]:
df=pd.DataFrame([("edho name", 23),("karthika deepam",100),("Devatha",75)])
df

0    1
0        edho name   23
1  karthika deepam  100
2          Devatha   75

In [21]:
df=pd.DataFrame([("edho name", 23),("karthika deepam",100),("Devatha",75)],columns=["Serial Name","Rating"])
df

Serial Name  Rating
0        edho name      23
1  karthika deepam     100
2          Devatha      75

In [22]:
df=pd.DataFrame([("edho name", 23),("karthika deepam",100),("Devatha",75)])
df.columns=["Serial Name","Rating"]
df

Serial Name  Rating
0        edho name      23
1  karthika deepam     100
2          Devatha      75

In [23]:
df=pd.DataFrame([("edho name", 23),("karthika deepam",100),("Devatha",75)])
df.columns=["Serial Name","Rating"]
df.index=['a','b','c']
df

Serial Name  Rating
a        edho name      23
b  karthika deepam     100
c          Devatha      75

In [24]:
a=np.arange(10).reshape(5,2)
df=pd.DataFrame(a)
df

0  1
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

In [25]:
d={"sno":[101,102,103,104,105],
  "sname":['a','b','c','d','e'],
   'sage':[23,26,25,12,34]
  }
df=pd.DataFrame(d)
df

sno sname  sage
0  101     a    23
1  102     b    26
2  103     c    25
3  104     d    12
4  105     e    34

In [26]:
df['sem1']=[45,43,23,24,50]
df['sem2']=[20,25,45,49,30]
df

sno sname  sage  sem1  sem2
0  101     a    23    45    20
1  102     b    26    43    25
2  103     c    25    23    45
3  104     d    12    24    49
4  105     e    34    50    30

In [27]:
df['sname']

0    a
1    b
2    c
3    d
4    e
Name: sname, dtype: object

In [28]:
type(df['sname'])

pandas.core.series.Series

In [29]:
df[['sname']]

sname
0     a
1     b
2     c
3     d
4     e

In [30]:
type(df[['sname']])

pandas.core.frame.DataFrame

In [31]:
df[['sno','sname']]

sno sname
0  101     a
1  102     b
2  103     c
3  104     d
4  105     e

In [32]:
# loc => location => index name
# iloc => index location => index position
df

sno sname  sage  sem1  sem2
0  101     a    23    45    20
1  102     b    26    43    25
2  103     c    25    23    45
3  104     d    12    24    49
4  105     e    34    50    30

In [33]:
df.loc[2]

sno      103
sname      c
sage      25
sem1      23
sem2      45
Name: 2, dtype: object

In [34]:
df.loc[[2]]

sno sname  sage  sem1  sem2
2  103     c    25    23    45

In [35]:
df.loc[:2]

sno sname  sage  sem1  sem2
0  101     a    23    45    20
1  102     b    26    43    25
2  103     c    25    23    45

In [36]:
df.loc[3:]

sno sname  sage  sem1  sem2
3  104     d    12    24    49
4  105     e    34    50    30

In [37]:
df.loc[[0,3]]

sno sname  sage  sem1  sem2
0  101     a    23    45    20
3  104     d    12    24    49

In [39]:
df.loc[:2,'sno':'sage']

sno sname  sage
0  101     a    23
1  102     b    26
2  103     c    25

In [40]:
df.iloc[:2,0:2]

sno sname
0  101     a
1  102     b

In [42]:
df.loc[2:,['sno','sname','sem2']]

sno sname  sem2
2  103     c    45
3  104     d    49
4  105     e    30

In [43]:
df.iloc[2:,[0,1,4]]

sno sname  sem2
2  103     c    45
3  104     d    49
4  105     e    30

In [45]:
df.loc[[0,3,4],['sno','sname','sem1']]
df.iloc[[0,3,4],[0,1,3]]

sno sname  sem1
0  101     a    45
3  104     d    24
4  105     e    50

In [46]:
df

sno sname  sage  sem1  sem2
0  101     a    23    45    20
1  102     b    26    43    25
2  103     c    25    23    45
3  104     d    12    24    49
4  105     e    34    50    30

In [47]:
df.drop('sem2',axis=1)

sno sname  sage  sem1
0  101     a    23    45
1  102     b    26    43
2  103     c    25    23
3  104     d    12    24
4  105     e    34    50

In [49]:
df.drop(2)

sno sname  sage  sem1  sem2
0  101     a    23    45    20
1  102     b    26    43    25
3  104     d    12    24    49
4  105     e    34    50    30

In [50]:
df

sno sname  sage  sem1  sem2
0  101     a    23    45    20
1  102     b    26    43    25
2  103     c    25    23    45
3  104     d    12    24    49
4  105     e    34    50    30

In [53]:
df[df['sem2']>=30]

sno sname  sage  sem1  sem2
2  103     c    25    23    45
3  104     d    12    24    49
4  105     e    34    50    30

In [55]:
df[df['sname']=='d']

sno sname  sage  sem1  sem2
3  104     d    12    24    49

In [58]:
sn=110
df[df['sno']==sn]

Empty DataFrame
Columns: [sno, sname, sage, sem1, sem2]
Index: []

In [60]:
df[(df['sem1']>=30) & (df['sem2']>=30)]

sno sname  sage  sem1  sem2
4  105     e    34    50    30

In [61]:
df

sno sname  sage  sem1  sem2
0  101     a    23    45    20
1  102     b    26    43    25
2  103     c    25    23    45
3  104     d    12    24    49
4  105     e    34    50    30

In [62]:
df['total']=df['sem1']+df['sem2']
df

sno sname  sage  sem1  sem2  total
0  101     a    23    45    20     65
1  102     b    26    43    25     68
2  103     c    25    23    45     68
3  104     d    12    24    49     73
4  105     e    34    50    30     80

In [63]:
df['avg']=df['total']//2
df

sno sname  sage  sem1  sem2  total  avg
0  101     a    23    45    20     65   32
1  102     b    26    43    25     68   34
2  103     c    25    23    45     68   34
3  104     d    12    24    49     73   36
4  105     e    34    50    30     80   40

In [65]:
df['grade']=np.where(df['avg']>=33,"P","F")
df

sno sname  sage  sem1  sem2  total  avg grade
0  101     a    23    45    20     65   32     F
1  102     b    26    43    25     68   34     P
2  103     c    25    23    45     68   34     P
3  104     d    12    24    49     73   36     P
4  105     e    34    50    30     80   40     P

In [66]:
df.columns

Index(['sno', 'sname', 'sage', 'sem1', 'sem2', 'total', 'avg', 'grade'], dtype='object')

In [68]:
df.sort_values('sage')

sno sname  sage  sem1  sem2  total  avg grade
3  104     d    12    24    49     73   36     P
0  101     a    23    45    20     65   32     F
2  103     c    25    23    45     68   34     P
1  102     b    26    43    25     68   34     P
4  105     e    34    50    30     80   40     P

In [69]:
df.sort_values('sage',ascending=False)

sno sname  sage  sem1  sem2  total  avg grade
4  105     e    34    50    30     80   40     P
1  102     b    26    43    25     68   34     P
2  103     c    25    23    45     68   34     P
0  101     a    23    45    20     65   32     F
3  104     d    12    24    49     73   36     P

In [72]:
df.min()
df.max()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
sno      5 non-null int64
sname    5 non-null object
sage     5 non-null int64
sem1     5 non-null int64
sem2     5 non-null int64
total    5 non-null int64
avg      5 non-null int64
grade    5 non-null object
dtypes: int64(6), object(2)
memory usage: 448.0+ bytes


In [73]:
df.describe()

sno       sage       sem1       sem2      total       avg
count    5.000000   5.000000   5.000000   5.000000   5.000000   5.00000
mean   103.000000  24.000000  37.000000  33.800000  70.800000  35.20000
std      1.581139   7.905694  12.589678  12.637247   5.890671   3.03315
min    101.000000  12.000000  23.000000  20.000000  65.000000  32.00000
25%    102.000000  23.000000  24.000000  25.000000  68.000000  34.00000
50%    103.000000  25.000000  43.000000  30.000000  68.000000  34.00000
75%    104.000000  26.000000  45.000000  45.000000  73.000000  36.00000
max    105.000000  34.000000  50.000000  49.000000  80.000000  40.00000

In [74]:
df.isnull().sum()

sno      0
sname    0
sage     0
sem1     0
sem2     0
total    0
avg      0
grade    0
dtype: int64